// KJB Pure Cambridge Edition — Psalm Superscriptions
// These are the headings/titles that appear above each Psalm in the KJB.
// Displayed italicised below the chapter title in the reader.
// Key: "Psalms:chapter"
// Psalms without a superscription are not listed.

export const SUBSCRIPTS = {
  // Psalm 10 has no header line — verse 1 itself starts "WHY standest..." with [why] and [thyself] bracketed
  // Psalms 2, 33, 43, 71 have no superscription in the PCE
  'Psalms:3':   'A Psalm of David, when he fled from Absalom his son.',
  'Psalms:4':   'To the chief Musician on Neginoth, A Psalm of David.',
  'Psalms:5':   'To the chief Musician upon Nehiloth, A Psalm of David.',
  'Psalms:6':   'To the chief Musician on Neginoth upon Sheminith, A Psalm of David.',
  'Psalms:7':   'Shiggaion of David, which he sang unto the LORD, concerning the words of Cush the Benjamite.',
  'Psalms:8':   'To the chief Musician upon Gittith, A Psalm of David.',
  'Psalms:9':   'To the chief Musician upon Muth-labben, A Psalm of David.',
  'Psalms:11':  'To the chief Musician, [A] [Psalm] of David.',
  'Psalms:12':  'To the chief Musician upon Sheminith, A Psalm of David.',
  'Psalms:13':  'To the chief Musician, A Psalm of David.',
  'Psalms:14':  'To the chief Musician, [A] [Psalm] of David.',
  'Psalms:15':  'A Psalm of David.',
  'Psalms:16':  'Michtam of David.',
  'Psalms:17':  'A Prayer of David.',
  'Psalms:18':  'To the chief Musician, [A] [Psalm] of David, the servant of the LORD, who spake unto the LORD the words of this song in the day [that] the LORD delivered him from the hand of all his enemies, and from the hand of Saul: And he said,',
  'Psalms:19':  'To the chief Musician, A Psalm of David.',
  'Psalms:20':  'To the chief Musician, A Psalm of David.',
  'Psalms:21':  'To the chief Musician, A Psalm of David.',
  'Psalms:22':  'To the chief Musician upon Aijeleth Shahar, A Psalm of David.',
  'Psalms:23':  'A Psalm of David.',
  'Psalms:24':  'A Psalm of David.',
  'Psalms:25':  '[A] [Psalm] of David.',
  'Psalms:26':  '[A] [Psalm] of David.',
  'Psalms:27':  '[A] [Psalm] of David.',
  'Psalms:28':  '[A] [Psalm] of David.',
  'Psalms:29':  'A Psalm of David.',
  'Psalms:30':  'A Psalm [and] Song [at] the dedication of the house of David.',
  'Psalms:31':  'To the chief Musician, A Psalm of David.',
  'Psalms:32':  '[A] [Psalm] of David, Maschil.',
  'Psalms:34':  '[A] [Psalm] of David, when he changed his behaviour before Abimelech; who drove him away, and he departed.',
  'Psalms:35':  '[A] [Psalm] of David.',
  'Psalms:36':  'To the chief Musician, [A] [Psalm] of David the servant of the LORD.',
  'Psalms:37':  '[A] [Psalm] of David.',
  'Psalms:38':  'A Psalm of David, to bring to remembrance.',
  'Psalms:39':  'To the chief Musician, [even] to Jeduthun, A Psalm of David.',
  'Psalms:40':  'To the chief Musician, A Psalm of David.',
  'Psalms:41':  'To the chief Musician, A Psalm of David.',
  'Psalms:42':  'To the chief Musician, Maschil, for the sons of Korah.',
  'Psalms:44':  'To the chief Musician for the sons of Korah, Maschil.',
  'Psalms:45':  'To the chief Musician upon Shoshannim, for the sons of Korah, Maschil, A Song of loves.',
  'Psalms:46':  'To the chief Musician for the sons of Korah, A Song upon Alamoth.',
  'Psalms:47':  'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:48':  'A Song [and] Psalm for the sons of Korah.',
  'Psalms:49':  'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:50':  'A Psalm of Asaph.',
  'Psalms:51':  'To the chief Musician, A Psalm of David, when Nathan the prophet came unto him, after he had gone in to Bath-sheba.',
  'Psalms:52':  'To the chief Musician, Maschil, [A] [Psalm] of David, when Doeg the Edomite came and told Saul, and said unto him, David is come to the house of Ahimelech.',
  'Psalms:53':  'To the chief Musician upon Mahalath, Maschil, [A] [Psalm] of David.',
  'Psalms:54':  'To the chief Musician on Neginoth, Maschil, [A] [Psalm] of David, when the Ziphims came and said to Saul, Doth not David hide himself with us?',
  'Psalms:55':  'To the chief Musician on Neginoth, Maschil, [A] [Psalm] of David.',
  'Psalms:56':  'To the chief Musician upon Jonath-elem-rechokim, Michtam of David, when the Philistines took him in Gath.',
  'Psalms:57':  'To the chief Musician, Al-taschith, Michtam of David, when he fled from Saul in the cave.',
  'Psalms:58':  'To the chief Musician, Al-taschith, Michtam of David.',
  'Psalms:59':  'To the chief Musician, Al-taschith, Michtam of David; when Saul sent, and they watched the house to kill him.',
  'Psalms:60':  'To the chief Musician upon Shushan-eduth, Michtam of David, to teach; when he strove with Aram-naharaim and with Aram-zobah, when Joab returned, and smote of Edom in the valley of salt twelve thousand.',
  'Psalms:61':  'To the chief Musician upon Neginah, [A] [Psalm] of David.',
  'Psalms:62':  'To the chief Musician, to Jeduthun, A Psalm of David.',
  'Psalms:63':  'A Psalm of David, when he was in the wilderness of Judah.',
  'Psalms:64':  'To the chief Musician, A Psalm of David.',
  'Psalms:65':  'To the chief Musician, A Psalm [and] Song of David.',
  'Psalms:66':  'To the chief Musician, A Song [or] Psalm.',
  'Psalms:67':  'To the chief Musician on Neginoth, A Psalm [or] Song.',
  'Psalms:68':  'To the chief Musician, A Psalm [or] Song of David.',
  'Psalms:69':  'To the chief Musician upon Shoshannim, [A] [Psalm] of David.',
  'Psalms:70':  'To the chief Musician, [A] [Psalm] of David, to bring to remembrance.',
  'Psalms:72':  '[A] [Psalm] for Solomon.',
  'Psalms:73':  'A Psalm of Asaph.',
  'Psalms:74':  'Maschil of Asaph.',
  'Psalms:75':  'To the chief Musician, Al-taschith, A Psalm [or] Song of Asaph.',
  'Psalms:76':  'To the chief Musician on Neginoth, A Psalm [or] Song of Asaph.',
  'Psalms:77':  'To the chief Musician, to Jeduthun, A Psalm of Asaph.',
  'Psalms:78':  'Maschil of Asaph.',
  'Psalms:79':  'A Psalm of Asaph.',
  'Psalms:80':  'To the chief Musician upon Shoshannim-Eduth, A Psalm of Asaph.',
  'Psalms:81':  'To the chief Musician upon Gittith, [A] [Psalm] of Asaph.',
  'Psalms:82':  'A Psalm of Asaph.',
  'Psalms:83':  'A Song [or] Psalm of Asaph.',
  'Psalms:84':  'To the chief Musician upon Gittith, A Psalm for the sons of Korah.',
  'Psalms:85':  'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:86':  'A Prayer of David.',
  'Psalms:87':  'A Psalm [or] Song for the sons of Korah.',
  'Psalms:88':  'A Song [or] Psalm for the sons of Korah, to the chief Musician upon Mahalath Leannoth, Maschil of Heman the Ezrahite.',
  'Psalms:89':  'Maschil of Ethan the Ezrahite.',
  'Psalms:90':  'A Prayer of Moses the man of God.',
  'Psalms:92':  'A Psalm [or] Song for the sabbath day.',
  'Psalms:98':  'A Psalm.',
  'Psalms:100': 'A Psalm of praise.',
  'Psalms:101': 'A Psalm of David.',
  'Psalms:102': 'A Prayer of the afflicted, when he is overwhelmed, and poureth out his complaint before the LORD.',
  'Psalms:103': '[A] [Psalm] of David.',
  'Psalms:108': 'A Song [or] Psalm of David.',
  'Psalms:109': 'To the chief Musician, A Psalm of David.',
  'Psalms:110': 'A Psalm of David.',
  'Psalms:120': 'A Song of degrees.',
  'Psalms:121': 'A Song of degrees.',
  'Psalms:122': 'A Song of degrees of David.',
  'Psalms:123': 'A Song of degrees.',
  'Psalms:124': 'A Song of degrees of David.',
  'Psalms:125': 'A Song of degrees.',
  'Psalms:126': 'A Song of degrees.',
  'Psalms:127': 'A Song of degrees for Solomon.',
  'Psalms:128': 'A Song of degrees.',
  'Psalms:129': 'A Song of degrees.',
  'Psalms:130': 'A Song of degrees.',
  'Psalms:131': 'A Song of degrees of David.',
  'Psalms:132': 'A Song of degrees.',
  'Psalms:133': 'A Song of degrees of David.',
  'Psalms:134': 'A Song of degrees.',
  'Psalms:138': '[A] [Psalm] of David.',
  'Psalms:139': 'To the chief Musician, A Psalm of David.',
  'Psalms:140': 'To the chief Musician, A Psalm of David.',
  'Psalms:141': 'A Psalm of David.',
  'Psalms:142': 'Maschil of David; A Prayer when he was in the cave.',
  'Psalms:143': 'A Psalm of David.',
  'Psalms:144': '[A] [Psalm] of David.',
  'Psalms:145': 'David\'s [Psalm] of praise.',
};

// Hardcoded correct verse 1 text for Psalms whose superscription appears as the
// unnumbered "verse 1" line in the PCE source file. The parser will replace whatever
// it parsed as verse 1 with this authoritative text, guaranteeing accuracy.
// Key: chapter number (integer). Value: exact PCE verse 1 text (with [brackets] for italics).
export const PSALM_VERSE_1 = {
  2:   'Why do the heathen rage, and the people imagine a vain thing?',
  3:   'LORD, how are they increased that trouble me! many [are] they that rise up against me.',
  4:   'Hear me when I call, O God of my righteousness: thou hast enlarged me [when I was] in distress; have mercy upon me, and hear my prayer.',
  5:   'Give ear to my words, O LORD, consider my meditation.',
  6:   'O LORD, rebuke me not in thine anger, neither chasten me in thy hot displeasure.',
  7:   'O LORD my God, in thee do I put my trust: save me from all them that persecute me, and deliver me:',
  8:   'O LORD our Lord, how excellent [is] thy name in all the earth! who hast set thy glory above the heavens.',
  9:   'I will praise [thee], O LORD, with my whole heart; I will shew forth all thy marvellous works.',
  11:  'In the LORD put I my trust: how say ye to my soul, Flee [as] a bird to your mountain?',
  12:  'Help, LORD; for the godly man ceaseth; for the faithful fail from among the children of men.',
  13:  'How long wilt thou forget me, O LORD? for ever? how long wilt thou hide thy face from me?',
  14:  'The fool hath said in his heart, [There is] no God. They are corrupt, they have done abominable works, [there is] none that doeth good.',
  15:  'LORD, who shall abide in thy tabernacle? who shall dwell in thy holy hill?',
  16:  'Preserve me, O God: for in thee do I put my trust.',
  17:  'Hear the right, O LORD, attend unto my cry, give ear unto my prayer, [that goeth] not out of feigned lips.',
  18:  'I will love thee, O LORD, my strength.',
  19:  'The heavens declare the glory of God; and the firmament sheweth his handywork.',
  20:  'The LORD hear thee in the day of trouble; the name of the God of Jacob defend thee;',
  21:  'The king shall joy in thy strength, O LORD; and in thy salvation how greatly shall he rejoice!',
  22:  'My God, my God, why hast thou forsaken me? [why art thou so] far from helping me, [and from] the words of my roaring?',
  23:  'The LORD [is] my shepherd; I shall not want.',
  24:  'The earth [is] the LORD\'s, and the fulness thereof; the world, and they that dwell therein.',
  25:  'Unto thee, O LORD, do I lift up my soul.',
  26:  'Judge me, O LORD; for I have walked in mine integrity: I have trusted also in the LORD; [therefore] I shall not slide.',
  27:  'The LORD [is] my light and my salvation; whom shall I fear? the LORD [is] the strength of my life; of whom shall I be afraid?',
  28:  'Unto thee will I cry, O LORD my rock; be not silent to me: lest, [if] thou be silent to me, I become like them that go down into the pit.',
  29:  'Give unto the LORD, O ye mighty, give unto the LORD glory and strength.',
  30:  'I will extol thee, O LORD; for thou hast lifted me up, and hast not made my foes to rejoice over me.',
  31:  'In thee, O LORD, do I put my trust; let me never be ashamed: deliver me in thy righteousness.',
  32:  'Blessed [is he whose] transgression [is] forgiven, [whose] sin [is] covered.',
  34:  'I will bless the LORD at all times: his praise shall continually be in my mouth.',
  35:  'Plead [my cause], O LORD, with them that strive with me: fight against them that fight against me.',
  36:  'The transgression of the wicked saith within my heart, [that there is] no fear of God before his eyes.',
  37:  'Fret not thyself because of evildoers, neither be thou envious against the workers of iniquity.',
  38:  'O LORD, rebuke me not in thy wrath: neither chasten me in thy hot displeasure.',
  39:  'I said, I will take heed to my ways, that I sin not with my tongue: I will keep my mouth with a bridle, while the wicked is before me.',
  40:  'I waited patiently for the LORD; and he inclined unto me, and heard my cry.',
  41:  'Blessed [is] he that considereth the poor: the LORD will deliver him in time of trouble.',
  42:  'As the hart panteth after the water brooks, so panteth my soul after thee, O God.',
  44:  'We have heard with our ears, O God, our fathers have told us, [what] work thou didst in their days, in the times of old.',
  45:  'My heart is inditing a good matter: I speak of the things which I have made touching the king: my tongue [is] the pen of a ready writer.',
  46:  'God [is] our refuge and strength, a very present help in trouble.',
  47:  'O clap your hands, all ye people; shout unto God with the voice of triumph.',
  48:  'Great [is] the LORD, and greatly to be praised in the city of our God, in the mountain of his holiness.',
  49:  'Hear this, all [ye] people; give ear, all [ye] inhabitants of the world:',
  50:  'The mighty God, [even] the LORD, hath spoken, and called the earth from the rising of the sun unto the going down thereof.',
  51:  'Have mercy upon me, O God, according to thy lovingkindness: according unto the multitude of thy tender mercies blot out my transgressions.',
  52:  'Why boastest thou thyself in mischief, O mighty man? the goodness of God [endureth] continually.',
  53:  'The fool hath said in his heart, There is no God. Corrupt are they, and have done abominable iniquity: [there is] none that doeth good.',
  54:  'Save me, O God, by thy name, and judge me by thy strength.',
  55:  'Give ear to my prayer, O God; and hide not thyself from my supplication.',
  56:  'Be merciful unto me, O God: for man would swallow me up; he fighting daily oppresseth me.',
  57:  'Be merciful unto me, O God, be merciful unto me: for my soul trusteth in thee: yea, in the shadow of thy wings will I make my refuge, until [these] calamities be overpast.',
  58:  'Do ye indeed speak righteousness, O congregation? do ye judge uprightly, O ye sons of men?',
  59:  'Deliver me from mine enemies, O my God: defend me from them that rise up against me.',
  60:  'O God, thou hast cast us off, thou hast scattered us, thou hast been displeased; O turn thyself to us again.',
  61:  'Hear my cry, O God; attend unto my prayer.',
  62:  'Truly my soul waiteth upon God: from him [cometh] my salvation.',
  63:  'O God, thou [art] my God; early will I seek thee: my soul thirsteth for thee, my flesh longeth for thee in a dry and thirsty land, where no water is;',
  64:  'Hear my voice, O God, in my prayer: preserve my life from fear of the enemy.',
  65:  'Praise waiteth for thee, O God, in Sion: and unto thee shall the vow be performed.',
  66:  'Make a joyful noise unto God, all ye lands:',
  67:  'God be merciful unto us, and bless us; and cause his face to shine upon us; Selah.',
  68:  'Let God arise, let his enemies be scattered: let them also that hate him flee before him.',
  69:  'Save me, O God; for the waters are come in unto [my] soul.',
  70:  'Make haste, O God, to deliver me; make haste to help me, O LORD.',
  72:  'Give the king thy judgments, O God, and thy righteousness unto the king\'s son.',
  73:  'Truly God [is] good to Israel, [even] to such as are of a clean heart.',
  74:  'O God, why hast thou cast [us] off for ever? [why] doth thine anger smoke against the sheep of thy pasture?',
  75:  'Unto thee, O God, do we give thanks, [unto thee] do we give thanks: for that thy name is near thy wondrous works declare.',
  76:  'In Judah [is] God known: his name [is] great in Israel.',
  77:  'I cried unto God with my voice, [even] unto God with my voice; and he gave ear unto me.',
  78:  'Give ear, O my people, [to] my law: incline your ears to the words of my mouth.',
  79:  'O God, the heathen are come into thine inheritance; thy holy temple have they defiled; they have laid Jerusalem on heaps.',
  80:  'Give ear, O Shepherd of Israel, thou that leadest Joseph like a flock; thou that dwellest [between] the cherubims, shine forth.',
  81:  'Sing aloud unto God our strength: make a joyful noise unto the God of Jacob.',
  82:  'God standeth in the congregation of the mighty; he judgeth among the gods.',
  83:  'Keep not thou silence, O God: hold not thy peace, and be not still, O God.',
  84:  'How amiable [are] thy tabernacles, O LORD of hosts!',
  85:  'LORD, thou hast been favourable unto thy land: thou hast brought back the captivity of Jacob.',
  86:  'Bow down thine ear, O LORD, hear me: for I [am] poor and needy.',
  87:  'His foundation [is] in the holy mountains.',
  88:  'O LORD God of my salvation, I have cried day [and] night before thee:',
  89:  'I will sing of the mercies of the LORD for ever: with my mouth will I make known thy faithfulness to all generations.',
  90:  'LORD, thou hast been our dwelling place in all generations.',
  92:  'It is a good thing to give thanks unto the LORD, and to sing praises unto thy name, O most High:',
  98:  'O sing unto the LORD a new song; for he hath done marvellous things: his right hand, and his holy arm, hath gotten him the victory.',
  100: 'Make a joyful noise unto the LORD, all ye lands.',
  101: 'I will sing of mercy and judgment: unto thee, O LORD, will I sing.',
  102: 'Hear my prayer, O LORD, and let my cry come unto thee.',
  103: 'Bless the LORD, O my soul: and all that is within me, [bless] his holy name.',
  108: 'O God, my heart is fixed; I will sing and give praise, even with my glory.',
  109: 'Hold not thy peace, O God of my praise;',
  110: 'The LORD said unto my Lord, Sit thou at my right hand, until I make thine enemies thy footstool.',
  120: 'In my distress I cried unto the LORD, and he heard me.',
  121: 'I will lift up mine eyes unto the hills, from whence cometh my help.',
  122: 'I was glad when they said unto me, Let us go into the house of the LORD.',
  123: 'Unto thee lift I up mine eyes, O thou that dwellest in the heavens.',
  124: 'If [it had not been] the LORD who was on our side, now may Israel say;',
  125: 'They that trust in the LORD [shall be] as mount Zion, [which] cannot be removed, [but] abideth for ever.',
  126: 'When the LORD turned again the captivity of Zion, we were like them that dream.',
  127: 'Except the LORD build the house, they labour in vain that build it: except the LORD keep the city, the watchman waketh [but] in vain.',
  128: 'Blessed [is] every one that feareth the LORD; that walketh in his ways.',
  129: 'Many a time have they afflicted me from my youth, may Israel now say:',
  130: 'Out of the depths have I cried unto thee, O LORD.',
  131: 'LORD, my heart is not haughty, nor mine eyes lofty: neither do I exercise myself in great matters, or in things too high for me.',
  132: 'LORD, remember David, and all his afflictions:',
  133: 'Behold, how good and how pleasant [it is] for brethren to dwell together in unity!',
  134: 'Behold, bless ye the LORD, all [ye] servants of the LORD, which by night stand in the house of the LORD.',
  138: 'I will praise thee with my whole heart: before the gods will I sing praise unto thee.',
  139: 'O LORD, thou hast searched me, and known [me].',
  140: 'Deliver me, O LORD, from the evil man: preserve me from the violent man;',
  141: 'LORD, I cry unto thee: make haste unto me; give ear unto my voice, when I cry unto thee.',
  142: 'I cried unto the LORD with my voice; with my voice unto the LORD did I make my supplication.',
  143: 'Hear my prayer, O LORD, give ear to my supplications: in thy faithfulness answer me, [and] in thy righteousness.',
  144: 'Blessed [be] the LORD my strength, which teacheth my hands to war, [and] my fingers to fight:',
  145: 'I will extol thee, my God, O king; and I will bless thy name for ever and ever.',
};

// Colophons — extracted from TEXT-PCE-127.txt (<<[...]>> markers), hardcoded here.
// Key: "BookApiName:chapter", value: colophon text string.
// These are rendered as a separate paragraph below the last verse, in italic.
export const COLOPHONS = {
  'Romans:16':          'Written to the Romans from Corinthus, [and sent] by Phebe servant of the church at Cenchrea.',
  '1 Corinthians:16':   'The first [epistle] to the Corinthians was written from Philippi by Stephanas, and Fortunatus, and Achaicus, and Timotheus.',
  '2 Corinthians:13':   'The second [epistle] to the Corinthians was written from Philippi, [a city] of Macedonia, by Titus and Lucas.',
  'Galatians:6':        'Unto the Galatians written from Rome.',
  'Ephesians:6':        'Written from Rome unto the Ephesians by Tychicus.',
  'Philippians:4':      'It was written to the Philippians from Rome by Epaphroditus.',
  'Colossians:4':       'Written from Rome to the Colossians by Tychicus and Onesimus.',
  '1 Thessalonians:5':  'The first [epistle] unto the Thessalonians was written from Athens.',
  '2 Thessalonians:3':  'The second [epistle] to the Thessalonians was written from Athens.',
  '1 Timothy:6':        'The first to Timothy was written from Laodicea, which is the chiefest city of Phrygia Pacatiana.',
  '2 Timothy:4':        'The second [epistle] unto Timotheus, ordained the first bishop of the church of the Ephesians, was written from Rome, when Paul was brought before Nero the second time.',
  'Titus:3':            'It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.',
  'Philemon:1':         'Written from Rome to Philemon, by Onesimus a servant.',
  'Hebrews:13':         'Written to the Hebrews from Italy by Timothy.',
};

// Psalm 119 — Hebrew acrostic section headings. Each 8-verse stanza begins
// with a Hebrew letter name (traditional KJB spelling). Keyed by the first
// verse number of the stanza; rendered as a small heading above that verse.
export const PSALM_119_SECTIONS = {
  1:   'ALEPH',
  9:   'BETH',
  17:  'GIMEL',
  25:  'DALETH',
  33:  'HE',
  41:  'VAU',
  49:  'ZAIN',
  57:  'CHETH',
  65:  'TETH',
  73:  'JOD',
  81:  'CAPH',
  89:  'LAMED',
  97:  'MEM',
  105: 'NUN',
  113: 'SAMECH',
  121: 'AIN',
  129: 'PE',
  137: 'TZADDI',
  145: 'KOPH',
  153: 'RESH',
  161: 'SCHIN',
  169: 'TAU',
};