// Maps modern/common words to their KJB archaic equivalents (and vice versa)
// Each entry: modern term -> array of KJB terms to also search
const SYNONYM_MAP = {
  // Animals
  'donkey': ['ass', 'asses'],
  'donkeys': ['asses', 'ass'],
  'horse': ['horse', 'horses'],
  'rooster': ['cock'],
  'rosters': ['cocks'],
  'rabbit': ['hare', 'hares'],
  'pig': ['swine', 'hog'],
  'pigs': ['swine', 'hogs'],
  'snake': ['serpent', 'serpents', 'adder'],
  'snakes': ['serpents', 'serpent', 'adders'],
  'lion': ['lion', 'lions'],
  'sheep': ['sheep', 'lamb', 'lambs', 'flock'],
  'goat': ['goat', 'goats', 'kid'],
  'goats': ['goats', 'goat', 'kids'],
  'cattle': ['kine', 'oxen', 'ox', 'bullock', 'bullocks', 'heifer'],
  'cow': ['kine', 'heifer', 'ox'],
  'cows': ['kine', 'heifers'],
  'bull': ['ox', 'bullock', 'oxen'],
  'bulls': ['oxen', 'bullocks'],
  'locust': ['locust', 'locusts'],
  'dove': ['dove', 'doves', 'pigeon'],
  'sparrow': ['sparrow', 'sparrows'],
  'raven': ['raven', 'ravens'],

  // Body & people
  'belly': ['belly', 'womb', 'bowels'],
  'stomach': ['belly', 'bowels'],
  'womb': ['womb', 'belly'],
  'heart': ['heart', 'hearts'],
  'throat': ['throat', 'neck'],
  'kidneys': ['reins'],
  'kidney': ['reins'],
  'bone': ['bone', 'bones'],
  'blood': ['blood'],
  'skin': ['skin', 'flesh'],
  'hair': ['hair', 'locks'],
  'forehead': ['forehead', 'brow'],
  'lips': ['lips', 'mouth'],
  'eyes': ['eyes', 'sight'],
  'ears': ['ears', 'hearing'],
  'tears': ['tears', 'weeping'],
  'old man': ['elder', 'elders', 'ancient'],
  'old woman': ['elder', 'aged'],
  'young man': ['young man', 'youth', 'lad'],
  'young woman': ['maid', 'maiden', 'damsel', 'virgin'],
  'girl': ['maid', 'damsel', 'maiden'],
  'boy': ['lad', 'youth', 'young man'],
  'child': ['child', 'children', 'infant', 'babe'],
  'children': ['children', 'sons', 'babes'],
  'baby': ['babe', 'infant', 'suckling'],
  'babies': ['babes', 'infants', 'sucklings'],
  'slave': ['servant', 'servants', 'bondman', 'bondwoman'],
  'slaves': ['servants', 'bondmen', 'bondwomen'],
  'servant': ['servant', 'servants'],
  'king': ['king', 'kings'],
  'queen': ['queen', 'queens'],
  'soldier': ['soldier', 'soldiers', 'warrior', 'man of war'],
  'soldiers': ['soldiers', 'warriors', 'men of war'],
  'priest': ['priest', 'priests'],
  'prophet': ['prophet', 'prophets'],
  'judge': ['judge', 'judges'],
  'widow': ['widow', 'widows'],
  'orphan': ['fatherless', 'orphan'],
  'stranger': ['stranger', 'strangers', 'sojourner', 'alien'],
  'foreigner': ['stranger', 'alien', 'sojourner'],
  'enemy': ['enemy', 'enemies', 'adversary', 'foe'],
  'enemies': ['enemies', 'adversaries', 'foes'],

  // Places / geography
  'cemetery': ['sepulchre', 'tomb', 'grave'],
  'grave': ['grave', 'sepulchre', 'tomb', 'pit'],
  'graves': ['graves', 'sepulchres', 'tombs'],
  'tomb': ['tomb', 'sepulchre', 'grave'],
  'prison': ['prison', 'dungeon', 'ward'],
  'city': ['city', 'cities'],
  'town': ['city', 'village', 'town'],
  'village': ['village', 'town'],
  'temple': ['temple', 'tabernacle', 'house of god'],
  'church': ['church', 'assembly', 'congregation'],
  'synagogue': ['synagogue', 'synagogues'],
  'sea': ['sea', 'seas', 'deep', 'waters'],
  'river': ['river', 'rivers', 'brook'],
  'mountain': ['mountain', 'mountains', 'mount', 'hill'],
  'mountains': ['mountains', 'hills', 'mount'],
  'desert': ['desert', 'wilderness', 'waste'],
  'wilderness': ['wilderness', 'desert'],
  'forest': ['forest', 'wood', 'woods'],
  'field': ['field', 'fields', 'plain'],
  'road': ['road', 'way', 'path', 'highway'],
  'path': ['path', 'way', 'paths'],

  // Actions / verbs
  'speak': ['speak', 'spake', 'saith', 'said', 'utter'],
  'spoke': ['spake', 'said'],
  'said': ['said', 'saith', 'spake'],
  'saw': ['saw', 'beheld', 'looked'],
  'see': ['see', 'behold', 'look'],
  'behold': ['behold', 'see', 'look'],
  'know': ['know', 'knew', 'knoweth'],
  'knew': ['knew', 'known'],
  'ask': ['ask', 'pray', 'beseech', 'enquire'],
  'pray': ['pray', 'prayed', 'supplicate'],
  'worship': ['worship', 'worshipped', 'bow'],
  'bow': ['bow', 'bowed', 'kneel', 'prostrate'],
  'bowed': ['bowed', 'fell down', 'prostrated'],
  'kneel': ['kneel', 'bow', 'bowed'],
  'listen': ['hearken', 'hear', 'heed'],
  'obey': ['obey', 'hearken', 'heed'],
  'disobey': ['disobey', 'rebel', 'transgress'],
  'sin': ['sin', 'transgress', 'iniquity', 'trespass'],
  'sins': ['sins', 'iniquities', 'transgressions', 'trespasses'],
  'sinned': ['sinned', 'transgressed', 'trespassed'],
  'forgive': ['forgive', 'forgave', 'pardon', 'remit'],
  'forgave': ['forgave', 'pardoned', 'forgiven'],
  'save': ['save', 'deliver', 'rescue', 'redeem'],
  'saved': ['saved', 'delivered', 'redeemed'],
  'heal': ['heal', 'healed', 'cure', 'made whole'],
  'healed': ['healed', 'made whole', 'cured'],
  'kill': ['kill', 'slay', 'slew', 'smite'],
  'killed': ['killed', 'slew', 'slain', 'smote'],
  'die': ['die', 'perish', 'give up the ghost'],
  'died': ['died', 'perished', 'gave up the ghost'],
  'born': ['born', 'begat', 'begotten'],
  'eat': ['eat', 'ate', 'did eat'],
  'ate': ['ate', 'did eat', 'eaten'],
  'drink': ['drink', 'drank', 'did drink'],
  'drank': ['drank', 'did drink'],
  'run': ['run', 'ran', 'fled'],
  'ran': ['ran', 'fled'],
  'walk': ['walk', 'walked', 'went'],
  'return': ['return', 'returned', 'turn again'],
  'bring': ['bring', 'brought'],
  'brought': ['brought', 'fetched'],
  'give': ['give', 'gave', 'given'],
  'gave': ['gave', 'given'],
  'take': ['take', 'took', 'taken'],
  'took': ['took', 'taken'],
  'make': ['make', 'made', 'create', 'form'],
  'made': ['made', 'created', 'formed'],
  'build': ['build', 'built', 'construct'],
  'built': ['built', 'builded'],
  'send': ['send', 'sent'],
  'sent': ['sent', 'send'],
  'cry': ['cry', 'cried', 'weep', 'wept'],
  'cried': ['cried', 'wept', 'lamented'],
  'weep': ['weep', 'wept', 'mourn'],
  'wept': ['wept', 'mourned'],
  'angry': ['angry', 'wrathful', 'wroth', 'wrath', 'indignation'],
  'anger': ['anger', 'wrath', 'indignation'],
  'happy': ['happy', 'blessed', 'joyful', 'merry'],
  'joy': ['joy', 'gladness', 'rejoice'],
  'sad': ['sad', 'sorrowful', 'grieved', 'mourning'],
  'fear': ['fear', 'afraid', 'dread', 'terror'],
  'afraid': ['afraid', 'feared', 'dread'],
  'love': ['love', 'loved', 'loveth', 'charity'],
  'hate': ['hate', 'hated', 'hateth', 'abhor'],
  'hated': ['hated', 'abhorred', 'despised'],
  'hope': ['hope', 'trust', 'faith'],
  'trust': ['trust', 'hope', 'faith', 'confidence'],
  'believe': ['believe', 'believed', 'faith', 'trust'],
  'believed': ['believed', 'trusted'],
  'doubt': ['doubt', 'doubted', 'waver', 'unbelief'],
  'repent': ['repent', 'repented', 'turn'],
  'confess': ['confess', 'confessed', 'acknowledge'],
  'bless': ['bless', 'blessed', 'blest'],
  'blessed': ['blessed', 'happy'],
  'curse': ['curse', 'cursed', 'accurse'],
  'cursed': ['cursed', 'accursed'],
  'anoint': ['anoint', 'anointed'],
  'baptize': ['baptize', 'baptise', 'baptized', 'baptised'],
  'baptized': ['baptized', 'baptised'],
  'preach': ['preach', 'preached', 'proclaim', 'declare'],
  'teach': ['teach', 'taught', 'instruct'],
  'taught': ['taught', 'instructed'],
  'judge': ['judge', 'judged', 'condemn'],
  'condemn': ['condemn', 'condemned'],
  'redeem': ['redeem', 'redeemed', 'ransom'],
  'redeemed': ['redeemed', 'ransomed'],

  // Spiritual / theological
  'devil': ['devil', 'satan', 'adversary', 'serpent'],
  'satan': ['satan', 'devil', 'adversary'],
  'demon': ['devil', 'unclean spirit', 'evil spirit'],
  'demons': ['devils', 'unclean spirits', 'evil spirits'],
  'angel': ['angel', 'angels'],
  'heaven': ['heaven', 'heavens', 'sky', 'paradise'],
  'hell': ['hell', 'hades', 'gehenna', 'pit', 'sheol', 'grave'],
  'god': ['god', 'lord', 'almighty'],
  'holy spirit': ['holy ghost', 'spirit of god', 'holy spirit'],
  'holy ghost': ['holy ghost', 'holy spirit', 'spirit of god'],
  'spirit': ['spirit', 'ghost'],
  'ghost': ['ghost', 'spirit'],
  'soul': ['soul', 'spirit', 'life'],
  'grace': ['grace', 'favour', 'mercy'],
  'mercy': ['mercy', 'grace', 'lovingkindness', 'compassion'],
  'righteousness': ['righteousness', 'justice', 'right'],
  'holy': ['holy', 'hallowed', 'sacred', 'sanctified'],
  'sanctify': ['sanctify', 'sanctified', 'holy', 'hallow'],
  'eternal': ['eternal', 'everlasting', 'forever', 'perpetual'],
  'everlasting': ['everlasting', 'eternal', 'forever'],
  'salvation': ['salvation', 'deliverance', 'saving'],
  'covenant': ['covenant', 'testament', 'promise', 'oath'],
  'sacrifice': ['sacrifice', 'offering', 'burnt offering'],
  'offering': ['offering', 'sacrifice', 'oblation'],
  'prayer': ['prayer', 'supplication', 'petition'],
  'faith': ['faith', 'belief', 'trust'],
  'law': ['law', 'commandment', 'statute', 'precept'],
  'commandment': ['commandment', 'commandments', 'law', 'precept'],
  'commandments': ['commandments', 'statutes', 'law'],
  'sin': ['sin', 'iniquity', 'transgression', 'trespass', 'wickedness'],
  'wickedness': ['wickedness', 'evil', 'iniquity', 'sin'],
  'evil': ['evil', 'wicked', 'iniquity', 'sin'],
  'truth': ['truth', 'faithful', 'verity'],
  'word': ['word', 'words', 'saying'],
  'sword': ['sword', 'swords', 'blade'],
  'shield': ['shield', 'buckler', 'armour'],
  'bread': ['bread', 'loaf', 'loaves'],
  'wine': ['wine', 'new wine', 'vinegar'],
  'water': ['water', 'waters', 'fountain', 'well'],
  'fire': ['fire', 'flame', 'burning'],
  'light': ['light', 'shine', 'lamp', 'candle'],
  'darkness': ['darkness', 'dark', 'shadow'],
  'glory': ['glory', 'honour', 'praise'],
  'praise': ['praise', 'glorify', 'extol', 'laud'],
  'hymn': ['hymn', 'song', 'psalm'],
  'song': ['song', 'psalm', 'hymn'],
  'promise': ['promise', 'covenant', 'oath', 'swear'],
  'heaven': ['heaven', 'heavens', 'firmament'],

  // Common modern synonyms for archaic KJB words
  'ass': ['ass', 'asses', 'donkey'],
  'harlot': ['harlot', 'harlots', 'whore', 'prostitute'],
  'prostitute': ['harlot', 'whore', 'harlots'],
  'whore': ['whore', 'harlot', 'harlots'],
  'fornication': ['fornication', 'sexual immorality', 'adultery'],
  'adultery': ['adultery', 'fornication'],
  'adulter': ['adultery', 'adulterer'],
  'swear': ['swear', 'oath', 'vow'],
  'oath': ['oath', 'vow', 'swear'],
  'vow': ['vow', 'oath', 'swear'],
  'famine': ['famine', 'hunger', 'dearth'],
  'hunger': ['hunger', 'famine', 'thirst'],
  'thirst': ['thirst', 'hunger'],
  'plague': ['plague', 'pestilence', 'disease'],
  'disease': ['disease', 'plague', 'pestilence', 'sickness'],
  'sick': ['sick', 'ill', 'infirm', 'disease'],
  'healing': ['healing', 'heal', 'healed', 'made whole'],
  'miracle': ['miracle', 'wonder', 'sign', 'mighty work'],
  'miracles': ['miracles', 'wonders', 'signs'],
  'wonder': ['wonder', 'miracle', 'sign'],
  'wonders': ['wonders', 'miracles', 'signs'],
  'parable': ['parable', 'proverb'],
  'prophecy': ['prophecy', 'vision', 'oracle'],
  'vision': ['vision', 'dream', 'prophecy'],
  'dream': ['dream', 'vision'],
  'wisdom': ['wisdom', 'understanding', 'knowledge'],
  'understanding': ['understanding', 'wisdom', 'knowledge'],
  'knowledge': ['knowledge', 'wisdom', 'understanding'],
  'rich': ['rich', 'riches', 'wealthy', 'abundance'],
  'wealth': ['wealth', 'riches', 'substance'],
  'poor': ['poor', 'needy', 'destitute', 'poverty'],
  'poverty': ['poverty', 'poor', 'needy'],
  'humble': ['humble', 'meek', 'lowly'],
  'meek': ['meek', 'humble', 'lowly'],
  'proud': ['proud', 'haughty', 'arrogant', 'pride'],
  'pride': ['pride', 'proud', 'haughty', 'arrogance'],
  'gentle': ['gentle', 'meek', 'mild'],
  'patient': ['patient', 'longsuffering', 'endure'],
  'patience': ['patience', 'longsuffering', 'endurance'],
  'long-suffering': ['longsuffering', 'patience'],
  'longsuffering': ['longsuffering', 'patience', 'long-suffering'],
};

/**
 * Given a user search term, returns an array of all terms to search for
 * (the original + any synonyms/archaic equivalents)
 */
export function expandSearchTerms(term) {
  const lower = term.toLowerCase().trim();
  const synonyms = SYNONYM_MAP[lower];
  if (!synonyms) return [lower];
  // Deduplicate, always include original
  const all = [lower, ...synonyms.map(s => s.toLowerCase())];
  return [...new Set(all)];
}