// Legacy Bible Reader - Data Constants
// Book abbreviations, names, chapter counts, and metadata for the KJB Pure Cambridge Edition

export const ABBR_TO_NAME = {
  'Ge':'Genesis','Ex':'Exodus','Le':'Leviticus','Nu':'Numbers','De':'Deuteronomy',
  'Jos':'Joshua','Jg':'Judges','Ru':'Ruth','1Sa':'1 Samuel','2Sa':'2 Samuel',
  '1Ki':'1 Kings','2Ki':'2 Kings','1Ch':'1 Chronicles','2Ch':'2 Chronicles',
  'Ezr':'Ezra','Ne':'Nehemiah','Es':'Esther','Job':'Job','Ps':'Psalms','Pr':'Proverbs',
  'Ec':'Ecclesiastes','Song':'Song of Solomon','Isa':'Isaiah','Jer':'Jeremiah',
  'La':'Lamentations','Eze':'Ezekiel','Da':'Daniel','Ho':'Hosea','Joe':'Joel',
  'Am':'Amos','Ob':'Obadiah','Jon':'Jonah','Mic':'Micah','Na':'Nahum',
  'Hab':'Habakkuk','Zep':'Zephaniah','Hag':'Haggai','Zec':'Zechariah','Mal':'Malachi',
  'Mt':'Matthew','Mr':'Mark','Lu':'Luke','Joh':'John','Ac':'Acts','Ro':'Romans',
  '1Co':'1 Corinthians','2Co':'2 Corinthians','Ga':'Galatians','Eph':'Ephesians',
  'Php':'Philippians','Col':'Colossians','1Th':'1 Thessalonians','2Th':'2 Thessalonians',
  '1Ti':'1 Timothy','2Ti':'2 Timothy','Tit':'Titus','Phm':'Philemon','Heb':'Hebrews',
  'Jas':'James','1Pe':'1 Peter','2Pe':'2 Peter','1Jo':'1 John','2Jo':'2 John',
  '3Jo':'3 John','Jude':'Jude','Re':'Revelation'
};

export const BOOK_ORDER = [
  'Genesis','Exodus','Leviticus','Numbers','Deuteronomy','Joshua','Judges','Ruth',
  '1 Samuel','2 Samuel','1 Kings','2 Kings','1 Chronicles','2 Chronicles','Ezra',
  'Nehemiah','Esther','Job','Psalms','Proverbs','Ecclesiastes','Song of Solomon',
  'Isaiah','Jeremiah','Lamentations','Ezekiel','Daniel','Hosea','Joel','Amos',
  'Obadiah','Jonah','Micah','Nahum','Habakkuk','Zephaniah','Haggai','Zechariah',
  'Malachi','Matthew','Mark','Luke','John','Acts','Romans','1 Corinthians',
  '2 Corinthians','Galatians','Ephesians','Philippians','Colossians',
  '1 Thessalonians','2 Thessalonians','1 Timothy','2 Timothy','Titus','Philemon',
  'Hebrews','James','1 Peter','2 Peter','1 John','2 John','3 John','Jude','Revelation'
];

export const FULL_BOOK_NAMES = {
  'Genesis':'The First Book of Moses, called Genesis',
  'Exodus':'The Second Book of Moses, called Exodus',
  'Leviticus':'The Third Book of Moses, called Leviticus',
  'Numbers':'The Fourth Book of Moses, called Numbers',
  'Deuteronomy':'The Fifth Book of Moses, called Deuteronomy',
  'Joshua':'The Book of Joshua',
  'Judges':'The Book of Judges',
  'Ruth':'The Book of Ruth',
  '1 Samuel':'The First Book of Samuel',
  '2 Samuel':'The Second Book of Samuel',
  '1 Kings':'The First Book of the Kings',
  '2 Kings':'The Second Book of the Kings',
  '1 Chronicles':'The First Book of the Chronicles',
  '2 Chronicles':'The Second Book of the Chronicles',
  'Ezra':'The Book of Ezra',
  'Nehemiah':'The Book of Nehemiah',
  'Esther':'The Book of Esther',
  'Job':'The Book of Job',
  'Psalms':'The Book of Psalms',
  'Proverbs':'The Proverbs',
  'Ecclesiastes':'Ecclesiastes',
  'Song of Solomon':'The Song of Solomon',
  'Isaiah':'The Book of Isaiah',
  'Jeremiah':'The Book of Jeremiah',
  'Lamentations':'The Lamentations of Jeremiah',
  'Ezekiel':'The Book of Ezekiel',
  'Daniel':'The Book of Daniel',
  'Hosea':'Hosea',
  'Joel':'Joel',
  'Amos':'Amos',
  'Obadiah':'Obadiah',
  'Jonah':'Jonah',
  'Micah':'Micah',
  'Nahum':'Nahum',
  'Habakkuk':'Habakkuk',
  'Zephaniah':'Zephaniah',
  'Haggai':'Haggai',
  'Zechariah':'Zechariah',
  'Malachi':'Malachi',
  'Matthew':'The Gospel According to Matthew',
  'Mark':'The Gospel According to Mark',
  'Luke':'The Gospel According to Luke',
  'John':'The Gospel According to John',
  'Acts':'The Acts of the Apostles',
  'Romans':'The Epistle to the Romans',
  '1 Corinthians':'The First Epistle to the Corinthians',
  '2 Corinthians':'The Second Epistle to the Corinthians',
  'Galatians':'The Epistle to the Galatians',
  'Ephesians':'The Epistle to the Ephesians',
  'Philippians':'The Epistle to the Philippians',
  'Colossians':'The Epistle to the Colossians',
  '1 Thessalonians':'The First Epistle to the Thessalonians',
  '2 Thessalonians':'The Second Epistle to the Thessalonians',
  '1 Timothy':'The First Epistle to Timothy',
  '2 Timothy':'The Second Epistle to Timothy',
  'Titus':'The Epistle to Titus',
  'Philemon':'The Epistle to Philemon',
  'Hebrews':'The Epistle to the Hebrews',
  'James':'The Epistle of James',
  '1 Peter':'The First General Epistle of Peter',
  '2 Peter':'The Second General Epistle of Peter',
  '1 John':'The First General Epistle of John',
  '2 John':'The Second General Epistle of John',
  '3 John':'The Third General Epistle of John',
  'Jude':'The General Epistle of Jude',
  'Revelation':'The Revelation of Saint John the Divine'
};

export const CHAPTER_COUNTS = {
  Genesis:50,Exodus:40,Leviticus:27,Numbers:36,Deuteronomy:34,Joshua:24,Judges:21,Ruth:4,
  '1 Samuel':31,'2 Samuel':24,'1 Kings':22,'2 Kings':25,'1 Chronicles':29,'2 Chronicles':36,
  Ezra:10,Nehemiah:13,Esther:10,Job:42,Psalms:150,Proverbs:31,Ecclesiastes:12,'Song of Solomon':8,
  Isaiah:66,Jeremiah:52,Lamentations:5,Ezekiel:48,Daniel:12,Hosea:14,Joel:3,Amos:9,Obadiah:1,
  Jonah:4,Micah:7,Nahum:3,Habakkuk:3,Zephaniah:3,Haggai:2,Zechariah:14,Malachi:4,
  Matthew:28,Mark:16,Luke:24,John:21,Acts:28,Romans:16,'1 Corinthians':16,'2 Corinthians':13,
  Galatians:6,Ephesians:6,Philippians:4,Colossians:4,'1 Thessalonians':5,'2 Thessalonians':3,
  '1 Timothy':6,'2 Timothy':4,Titus:3,Philemon:1,Hebrews:13,James:5,'1 Peter':5,'2 Peter':3,
  '1 John':5,'2 John':1,'3 John':1,Jude:1,Revelation:22
};

export const SUBSCRIPTS = {
  'Psalms:3':'A Psalm of David, when he fled from Absalom his son.',
  'Psalms:4':'To the chief Musician on Neginoth, A Psalm of David.',
  'Psalms:5':'To the chief Musician upon Nehiloth, A Psalm of David.',
  'Psalms:6':'To the chief Musician on Neginoth upon Sheminith, A Psalm of David.',
  'Psalms:7':'Shiggaion of David, which he sang unto the LORD, concerning the words of Cush the Benjamite.',
  'Psalms:8':'To the chief Musician upon Gittith, A Psalm of David.',
  'Psalms:9':'To the chief Musician upon Muth-labben, A Psalm of David.',
  'Psalms:11':'To the chief Musician, [A] [Psalm] of David.',
  'Psalms:12':'To the chief Musician upon Sheminith, A Psalm of David.',
  'Psalms:13':'To the chief Musician, A Psalm of David.',
  'Psalms:14':'To the chief Musician, [A] [Psalm] of David.',
  'Psalms:15':'A Psalm of David.',
  'Psalms:16':'Michtam of David.',
  'Psalms:17':'A Prayer of David.',
  'Psalms:18':'To the chief Musician, [A] [Psalm] of David, the servant of the LORD, who spake unto the LORD the words of this song in the day [that] the LORD delivered him from the hand of all his enemies, and from the hand of Saul: And he said,',
  'Psalms:19':'To the chief Musician, A Psalm of David.',
  'Psalms:20':'To the chief Musician, A Psalm of David.',
  'Psalms:21':'To the chief Musician, A Psalm of David.',
  'Psalms:22':'To the chief Musician upon Aijeleth Shahar, A Psalm of David.',
  'Psalms:23':'A Psalm of David.',
  'Psalms:24':'A Psalm of David.',
  'Psalms:25':'[A] [Psalm] of David.',
  'Psalms:26':'[A] [Psalm] of David.',
  'Psalms:27':'[A] [Psalm] of David.',
  'Psalms:28':'[A] [Psalm] of David.',
  'Psalms:29':'A Psalm of David.',
  'Psalms:30':'A Psalm [and] Song [at] the dedication of the house of David.',
  'Psalms:31':'To the chief Musician, A Psalm of David.',
  'Psalms:32':'[A] [Psalm] of David, Maschil.',
  'Psalms:34':'[A] [Psalm] of David, when he changed his behaviour before Abimelech; who drove him away, and he departed.',
  'Psalms:35':'[A] [Psalm] of David.',
  'Psalms:36':'To the chief Musician, [A] [Psalm] of David the servant of the LORD.',
  'Psalms:37':'[A] [Psalm] of David.',
  'Psalms:38':'A Psalm of David, to bring to remembrance.',
  'Psalms:39':'To the chief Musician, [even] to Jeduthun, A Psalm of David.',
  'Psalms:40':'To the chief Musician, A Psalm of David.',
  'Psalms:41':'To the chief Musician, A Psalm of David.',
  'Psalms:42':'To the chief Musician, Maschil, for the sons of Korah.',
  'Psalms:44':'To the chief Musician for the sons of Korah, Maschil.',
  'Psalms:45':'To the chief Musician upon Shoshannim, for the sons of Korah, Maschil, A Song of loves.',
  'Psalms:46':'To the chief Musician for the sons of Korah, A Song upon Alamoth.',
  'Psalms:47':'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:48':'A Song [and] Psalm for the sons of Korah.',
  'Psalms:49':'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:50':'A Psalm of Asaph.',
  'Psalms:51':'To the chief Musician, A Psalm of David, when Nathan the prophet came unto him, after he had gone in to Bath-sheba.',
  'Psalms:52':'To the chief Musician, Maschil, [A] [Psalm] of David, when Doeg the Edomite came and told Saul, and said unto him, David is come to the house of Ahimelech.',
  'Psalms:53':'To the chief Musician upon Mahalath, Maschil, [A] [Psalm] of David.',
  'Psalms:54':'To the chief Musician on Neginoth, Maschil, [A] [Psalm] of David, when the Ziphims came and said to Saul, Doth not David hide himself with us?',
  'Psalms:55':'To the chief Musician on Neginoth, Maschil, [A] [Psalm] of David.',
  'Psalms:56':'To the chief Musician upon Jonath-elem-rechokim, Michtam of David, when the Philistines took him in Gath.',
  'Psalms:57':'To the chief Musician, Al-taschith, Michtam of David, when he fled from Saul in the cave.',
  'Psalms:58':'To the chief Musician, Al-taschith, Michtam of David.',
  'Psalms:59':'To the chief Musician, Al-taschith, Michtam of David; when Saul sent, and they watched the house to kill him.',
  'Psalms:60':'To the chief Musician upon Shushan-eduth, Michtam of David, to teach; when he strove with Aram-naharaim and with Aram-zobah, when Joab returned, and smote of Edom in the valley of salt twelve thousand.',
  'Psalms:61':'To the chief Musician upon Neginah, [A] [Psalm] of David.',
  'Psalms:62':'To the chief Musician, to Jeduthun, A Psalm of David.',
  'Psalms:63':'A Psalm of David, when he was in the wilderness of Judah.',
  'Psalms:64':'To the chief Musician, A Psalm of David.',
  'Psalms:65':'To the chief Musician, A Psalm [and] Song of David.',
  'Psalms:66':'To the chief Musician, A Song [or] Psalm.',
  'Psalms:67':'To the chief Musician on Neginoth, A Psalm [or] Song.',
  'Psalms:68':'To the chief Musician, A Psalm [or] Song of David.',
  'Psalms:69':'To the chief Musician upon Shoshannim, [A] [Psalm] of David.',
  'Psalms:70':'To the chief Musician, [A] [Psalm] of David, to bring to remembrance.',
  'Psalms:72':'[A] [Psalm] for Solomon.',
  'Psalms:73':'A Psalm of Asaph.',
  'Psalms:74':'Maschil of Asaph.',
  'Psalms:75':'To the chief Musician, Al-taschith, A Psalm [or] Song of Asaph.',
  'Psalms:76':'To the chief Musician on Neginoth, A Psalm [or] Song of Asaph.',
  'Psalms:77':'To the chief Musician, to Jeduthun, A Psalm of Asaph.',
  'Psalms:78':'Maschil of Asaph.',
  'Psalms:79':'A Psalm of Asaph.',
  'Psalms:80':'To the chief Musician upon Shoshannim-Eduth, A Psalm of Asaph.',
  'Psalms:81':'To the chief Musician upon Gittith, [A] [Psalm] of Asaph.',
  'Psalms:82':'A Psalm of Asaph.',
  'Psalms:83':'A Song [or] Psalm of Asaph.',
  'Psalms:84':'To the chief Musician upon Gittith, A Psalm for the sons of Korah.',
  'Psalms:85':'To the chief Musician, A Psalm for the sons of Korah.',
  'Psalms:86':'A Prayer of David.',
  'Psalms:87':'A Psalm [or] Song for the sons of Korah.',
  'Psalms:88':'A Song [or] Psalm for the sons of Korah, to the chief Musician upon Mahalath Leannoth, Maschil of Heman the Ezrahite.',
  'Psalms:89':'Maschil of Ethan the Ezrahite.',
  'Psalms:90':'A Prayer of Moses the man of God.',
  'Psalms:92':'A Psalm [or] Song for the sabbath day.',
  'Psalms:98':'A Psalm.',
  'Psalms:100':'A Psalm of praise.',
  'Psalms:101':'A Psalm of David.',
  'Psalms:102':'A Prayer of the afflicted, when he is overwhelmed, and poureth out his complaint before the LORD.',
  'Psalms:103':'[A] [Psalm] of David.',
  'Psalms:108':'A Song [or] Psalm of David.',
  'Psalms:109':'To the chief Musician, A Psalm of David.',
  'Psalms:110':'A Psalm of David.',
  'Psalms:120':'A Song of degrees.',
  'Psalms:121':'A Song of degrees.',
  'Psalms:122':'A Song of degrees of David.',
  'Psalms:123':'A Song of degrees.',
  'Psalms:124':'A Song of degrees of David.',
  'Psalms:125':'A Song of degrees.',
  'Psalms:126':'A Song of degrees.',
  'Psalms:127':'A Song of degrees for Solomon.',
  'Psalms:128':'A Song of degrees.',
  'Psalms:129':'A Song of degrees.',
  'Psalms:130':'A Song of degrees.',
  'Psalms:131':'A Song of degrees of David.',
  'Psalms:132':'A Song of degrees.',
  'Psalms:133':'A Song of degrees of David.',
  'Psalms:134':'A Song of degrees.',
  'Psalms:138':'[A] [Psalm] of David.',
  'Psalms:139':'To the chief Musician, A Psalm of David.',
  'Psalms:140':'To the chief Musician, A Psalm of David.',
  'Psalms:141':'A Psalm of David.',
  'Psalms:142':'Maschil of David; A Prayer when he was in the cave.',
  'Psalms:143':'A Psalm of David.',
  'Psalms:144':'[A] [Psalm] of David.',
  'Psalms:145':"David's [Psalm] of praise."
};

export const COLOPHONS = {
  'Romans:16':'Written to the Romans from Corinthus, [and sent] by Phebe servant of the church at Cenchrea.',
  '1 Corinthians:16':'The first [epistle] to the Corinthians was written from Philippi by Stephanas, and Fortunatus, and Achaicus, and Timotheus.',
  '2 Corinthians:13':'The second [epistle] to the Corinthians was written from Philippi, [a city] of Macedonia, by Titus and Lucas.',
  'Galatians:6':'Unto the Galatians written from Rome.',
  'Ephesians:6':'Written from Rome unto the Ephesians by Tychicus.',
  'Philippians:4':'It was written to the Philippians from Rome by Epaphroditus.',
  'Colossians:4':'Written from Rome to the Colossians by Tychicus and Onesimus.',
  '1 Thessalonians:5':'The first [epistle] unto the Thessalonians was written from Athens.',
  '2 Thessalonians:3':'The second [epistle] to the Thessalonians was written from Athens.',
  '1 Timothy:6':'The first to Timothy was written from Laodicea, which is the chiefest city of Phrygia Pacatiana.',
  '2 Timothy:4':'The second [epistle] unto Timotheus, ordained the first bishop of the church of the Ephesians, was written from Rome, when Paul was brought before Nero the second time.',
  'Titus:3':'It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.',
  'Philemon:1':'Written from Rome to Philemon, by Onesimus a servant.',
  'Hebrews:13':'Written to the Hebrews from Italy by Timothy.'
};

export const PREACHERS = [
  { name: 'Robert Breaker', desc: 'KJB missionary evangelist, rightly dividing the word of truth.', links: ['https://www.youtube.com/@Robertbreaker3','https://www.tiktok.com/@robertbreaker','https://thecloudchurch.org/'] },
  { name: 'Robert Potthoff', desc: 'Big Red Preacher — KJB soul winner.', links: ['https://www.instagram.com/robert.potthoff/','https://www.facebook.com/potthoff87','https://www.instagram.com/big_red_preacher','https://mission1611.com/'] },
  { name: 'Joseph Gonzalez', desc: 'KJB Elites — faithful preacher of the word.', links: ['https://youtube.com/@josephgonzalez3','https://www.tiktok.com/@joyfullychurch','https://joyfullychurch.univer.se/'] },
  { name: 'Ryan Poff', desc: 'Seed of Hope Church — KJB pastor and preacher.', links: ['https://www.seedofhopechurch.org/','https://youtube.com/@ryan_poff','https://www.tiktok.com/@ryan_sohc'] },
  { name: 'Skyler (AV1611 Ministry)', desc: 'AV1611 Ministry — KJB defence and preaching.', links: ['https://www.tiktok.com/@av1611ministries','https://youtube.com/@av1611ministries'] },
  { name: 'Crown of Thorns', desc: 'KJB preaching ministry on YouTube.', links: ['https://www.youtube.com/@CrownOfThorns'] },
  { name: 'Paul Johnson', desc: 'Biblical Salvation — KJB preaching and Bible teaching.', links: ['https://www.tiktok.com/@pauljohnson9632','https://youtube.com/@biblicalsalvation'] },
  { name: 'CPR Missions', desc: 'Church Planting and Revival Missions — soul winning and church planting.', links: ['https://www.youtube.com/channel/UCWBR5DmAi2XPMFRtb-wqHwg','https://www.tiktok.com/@cprmissions','https://www.facebook.com/CPRmission/','https://www.instagram.com/cprmissions/'] },
  { name: 'James Bray', desc: 'KJB preacher and Bible teacher on YouTube.', links: ['https://youtube.com/@jamesbrayall3'] }
];

export const WHY_KJB_CONTENT = [
  {
    title: "The Word of God Will Keep Its Infallibility",
    text: "A historical book demonstrating that the King James Bible is the infallible, preserved Word of God in the English language. Full text available on Archive.org.",
    links: [{ url: 'https://archive.org/details/wordgodwillkeepi0000faus', label: 'Read on Archive.org' }]
  },
  {
    title: "Warning on the NKJV",
    text: "You are more than welcome to purchase a King James Bible from the Dollar Store or any Bible retailer without worrying about errors. However, please note: the NKJV is not the same as the King James Bible. Please check out this resource to learn more and do your own research.",
    links: [{ url: 'https://www.scionofzion.com/nkjv.htm', label: 'NKJV Comparison' }]
  },
  {
    title: "Textus Receptus Bibles",
    text: "Research on the Textus Receptus — the Greek text underlying the King James Bible.",
    links: [{ url: 'https://textusreceptusbibles.com/Differences_Between_Textus_Receptus_and_NaUbs', label: 'Read comparison' }]
  }
];

export const RESOURCES = [
  {
    category: "How to Read the Bible",
    items: [{
      title: "AV Publications",
      desc: "Books and resources for King James Bible believers.",
      url: "https://avpublications.com/",
      label: "avpublications.com"
    }]
  },
  {
    category: "KJB Defence",
    items: [
      {
        title: "King James Bible: Pure Cambridge Edition & Free Download",
        desc: "The definitive electronic text of the Pure Cambridge Edition of the KJB — bibleprotector.com. Free downloads available in PDF, ePub, and TXT formats.",
        url: "https://www.bibleprotector.com",
        label: "bibleprotector.com"
      },
      {
        title: "The Word of God Will Keep Its Infallibility (Archive.org)",
        desc: "Historical book demonstrating that the King James Bible is infallible — full text available on Archive.org.",
        url: "https://archive.org/details/wordgodwillkeepi0000faus/page/18/mode/1up?q=%22King+James+Bible+is+infallible%22",
        label: "Read on Archive.org"
      },
      {
        title: "KJV Compare",
        desc: "Go through hundreds of changes made in modern versions of the Bible — verse-by-verse.",
        url: "https://kjvcompare.com/",
        label: "kjvcompare.com"
      }
    ]
  }
];